web:
  build: .
  expose:
    - "5000"
  links:
    - redis

redis:
  image: redis
  command: redis-server --appendonly yes
  volumes:
    - "redisdata:/data"

lb: 
  image: tutum/haproxy
  links:
      - web
  ports:
      - "80:80"
  environment:
      - BACKEND_PORT=5000
      - BALANCE=roundrobin